# Generated by Django 5.0.4 on 2024-04-25 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_restaurent_cuisinesrest_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisinesrest',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurants', to_field='rest_id'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='city_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.city', to_field='city_code'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.country', to_field='country_code'),
        ),
    ]
