# Generated by Django 5.0.4 on 2024-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_cuisinesrest_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rest_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
