# Generated by Django 5.0.4 on 2024-04-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_restaurants_rest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
