# Generated by Django 5.0.4 on 2024-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_restaurants_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
