# Generated by Django 5.0.4 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_restaurants_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lattitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
