# Generated by Django 5.0.4 on 2024-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_restaurants_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rest_id',
            field=models.IntegerField(unique=True),
        ),
    ]
